apiVersion: v1
kind: Namespace
metadata:
  name: ujkljkljk-dev
  labels:
    environment-id: env_5d4901df-6928-45ca-84ac-f30babdd2bc8
    project-id: project_2974f9b6-45b0-4b52-9fa3-6a57b5f41663
    project-name: ujkljkljk
    environment-name: dev
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
